# Generated by Django 2.0.10 on 2019-01-17 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inst',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aapp.Country'),
        ),
        migrations.AddField(
            model_name='inst',
            name='hist_from',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='inst',
            name='hist_last_updated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='inst',
            name='hist_to',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='inst',
            name='history',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='inst',
            name='industry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aapp.Industry'),
        ),
        migrations.AddField(
            model_name='inst',
            name='inst_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aapp.InstType'),
        ),
        migrations.AddField(
            model_name='inst',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='inst',
            name='screen_last_updated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='inst',
            name='ticker',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='insttype',
            name='name',
            field=models.CharField(choices=[('stock', 'Stock')], max_length=20),
        ),
    ]
