# Generated by Django 2.0.10 on 2019-01-17 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aapp', '0002_auto_20190117_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inst',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
