# Generated by Django 2.0.10 on 2019-01-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aapp', '0004_portfolio_share'),
    ]

    operations = [
        migrations.CreateModel(
            name='FabricStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wip', models.BooleanField(default=False)),
                ('task', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='inst',
            name='history_scanned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inst',
            name='screen_scanned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inst',
            name='up_to_date',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='evoreport',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='evoreport',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
