# Generated by Django 2.0.10 on 2019-01-20 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aapp', '0005_auto_20190119_1112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inst',
            old_name='name',
            new_name='company',
        ),
        migrations.AddField(
            model_name='inst',
            name='dividend',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='inst',
            name='fwd_pe',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='inst',
            name='market_cap',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='inst',
            name='pb',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='inst',
            name='pe',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='inst',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='inst',
            name='recom',
            field=models.FloatField(null=True),
        ),
    ]
