# Generated by Django 2.0.10 on 2019-01-24 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aapp', '0006_auto_20190120_0330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
                ('description', models.TextField(default=None)),
                ('screen_params', models.CharField(default=None, max_length=100)),
                ('portfolio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aapp.Portfolio')),
            ],
        ),
    ]
