# Generated by Django 2.0.10 on 2019-01-24 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aapp', '0007_advisor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advisor',
            name='portfolio',
        ),
        migrations.DeleteModel(
            name='Advisor',
        ),
    ]
