# Generated by Django 2.0.10 on 2019-01-25 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aapp', '0008_auto_20190124_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('amount', models.IntegerField(default=0)),
                ('balance', models.IntegerField(default=0)),
                ('start_date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='portfolio',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='capital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aapp.Capital'),
        ),
    ]
