# Generated by Django 2.0.10 on 2019-01-25 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aapp', '0009_auto_20190125_0419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capital',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
