# Generated by Django 2.0.10 on 2019-01-25 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aapp', '0010_auto_20190125_0431'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawScan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('data', models.TextField(null=True)),
                ('scan_type', models.CharField(max_length=20, null=True)),
                ('author', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='capital',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
