# Generated by Django 2.0.10 on 2019-01-26 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aapp', '0011_auto_20190125_0554'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawscan',
            name='query',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
