# Generated by Django 2.0.10 on 2019-02-01 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aapp', '0014_auto_20190126_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='inst',
            name='eps',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='inst',
            name='eps_next_year',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='inst',
            name='eps_next_year_growth',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='inst',
            name='eps_this_year_growth',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='inst',
            name='peg',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='inst',
            name='sales_past_5years_growth',
            field=models.FloatField(null=True),
        ),
    ]
