# Generated by Django 2.0.10 on 2019-02-04 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aapp', '0015_auto_20190201_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='inst',
            name='inst_own',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='inst',
            name='net_margin',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='inst',
            name='op_margin',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='inst',
            name='roa',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='inst',
            name='roe',
            field=models.FloatField(null=True),
        ),
    ]
