# Generated by Django 2.2.4 on 2019-09-02 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aapp', '0017_auto_20190902_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawdata',
            name='query',
            field=models.TextField(null=True),
        ),
    ]
