# Generated by Django 2.2.4 on 2019-09-14 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aapp', '0018_rawdata_query'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundamentalEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10, null=True)),
                ('simfin_id', models.IntegerField(null=True)),
                ('industry_code', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('value', models.FloatField(null=True)),
                ('date', models.DateField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='inst',
            name='ticker',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
