# Generated by Django 2.2.4 on 2019-09-20 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aapp', '0021_apicall'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o', models.FloatField(null=True)),
                ('c', models.FloatField(null=True)),
                ('h', models.FloatField(null=True)),
                ('l', models.FloatField(null=True)),
                ('v', models.IntegerField(null=True)),
                ('s', models.CharField(max_length=10, null=True)),
                ('d', models.DateField(null=True)),
            ],
        ),
    ]
