# Generated by Django 2.2.4 on 2019-09-28 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aapp', '0022_bar'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FundamentalEvent',
            new_name='Metric',
        ),
        migrations.RenameModel(
            old_name='Share',
            new_name='Pie',
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100, null=True)),
                ('symbol', models.CharField(max_length=10, null=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aapp.Country')),
                ('industry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aapp.Industry')),
            ],
        ),
    ]
