# Generated by Django 2.2.4 on 2019-09-28 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aapp', '0023_auto_20190928_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pie',
            name='inst',
        ),
        migrations.AddField(
            model_name='pie',
            name='stock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aapp.Stock'),
        ),
        migrations.DeleteModel(
            name='Inst',
        ),
    ]
