# Generated by Django 2.2.4 on 2019-09-28 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aapp', '0024_auto_20190928_1658'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InstType',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='country',
        ),
    ]
