# Generated by Django 2.2.4 on 2019-09-28 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aapp', '0025_auto_20190928_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='bar',
            name='stock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aapp.Stock'),
        ),
    ]
