# Generated by Django 2.2.4 on 2019-09-29 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aapp', '0026_bar_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bar',
            name='s',
        ),
    ]
