# Generated by Django 2.2.4 on 2019-09-29 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aapp', '0027_remove_bar_s'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(null=True)),
                ('date', models.DateField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='apicall',
            name='response',
        ),
        migrations.DeleteModel(
            name='FabricStatus',
        ),
        migrations.DeleteModel(
            name='ApiCall',
        ),
        migrations.DeleteModel(
            name='RawData',
        ),
    ]
