# Generated by Django 2.2.4 on 2019-09-29 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aapp', '0028_auto_20190929_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='bar',
            name='day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aapp.Day'),
        ),
    ]
