# Generated by Django 2.2.4 on 2019-09-29 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aapp', '0029_bar_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bar',
            name='day',
            field=models.IntegerField(null=True),
        ),
    ]
