# Generated by Django 2.2.4 on 2019-09-29 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aapp', '0030_auto_20190929_1254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metric',
            old_name='industry_code',
            new_name='simfin_industry_code',
        ),
        migrations.RemoveField(
            model_name='metric',
            name='date',
        ),
        migrations.RemoveField(
            model_name='metric',
            name='symbol',
        ),
        migrations.AddField(
            model_name='metric',
            name='day',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='metric',
            name='stock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aapp.Stock'),
        ),
    ]
