# Generated by Django 2.2.4 on 2019-09-29 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aapp', '0031_auto_20190929_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metric',
            name='day',
        ),
        migrations.AddField(
            model_name='metric',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
