# Generated by Django 2.2.6 on 2019-11-04 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aapp', '0032_auto_20190929_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='day',
            field=models.IntegerField(null=True),
        ),
    ]
