# Generated by Django 2.2.6 on 2019-11-04 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aapp', '0033_metric_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='imprecise',
            field=models.BooleanField(default=False),
        ),
    ]
